#!/usr/bin/perl -w

# Generate usys.S, the stubs for syscalls.

print "# generated by usys.pl - do not edit\n";

print "#include \"kernel/syscall.h\"\n";

# 定义了一个名为 entry 的子程序，用于自动生成汇编代码，实现系统调用的包装函数
sub entry {
    my $name = shift; # 获取传入的系统调用名称参数
    print ".global $name\n"; # 声明该符号为全局符号，便于链接器识别
    print "${name}:\n"; # 定义系统调用包装函数的入口
    # 根据 RISC-V 调用约定，a7 用于传递系统调用号
    print " li a7, SYS_${name}\n"; # 生成一条汇编指令，将系统调用号（SYS_${name}）加载到 a7 寄存器
    print " ecall\n"; # 触发从用户态到内核态的系统调用陷入
    print " ret\n"; # 系统调用返回后恢复现场
}

# 下面是对各个系统调用的包装函数的生成调用
# 例如，生成 fork 系统调用的包装函数
# .global fork
# fork:
#   li a7, SYS_fork
#   ecall
#   ret
entry("fork");
entry("exit");
entry("wait");
entry("pipe");
entry("read");
entry("write");
entry("close");
entry("kill");
entry("exec");
entry("open");
entry("mknod");
entry("unlink");
entry("fstat");
entry("link");
entry("mkdir");
entry("chdir");
entry("dup");
entry("getpid");
entry("sbrk");
entry("sleep");
entry("uptime");
